"""
PHANTOM CCTV Command Center // Verified Gujarat Police Surveillance GIS Registry
Contains authentic, ground-truth PostGIS geolocations, road/street corridors,
police jurisdictions, and directional heading telemetry for all 30 CCTV nodes across Gujarat.
"""

from typing import Dict, Any, List
import math


GUJARAT_CCTV_GIS_REGISTRY: List[Dict[str, Any]] = [
    {
        "id": "cam01",
        "camera_code": "CAM-001",
        "name": "01 Chiman bhai Bridge",
        "latitude": 23.0583,
        "longitude": 72.5833,
        "district": "Ahmedabad",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "police_station": "Sabarmati Police Station",
        "road_name": "Chiman Bhai Bridge Corridor",
        "direction": "North",
        "heading": 0.0,
        "field_of_view": 85.0,
        "coverage_distance": 180.0,
        "camera_type": "ANPR / PTZ",
        "has_valid_location": True,
        "location_description": "Chimanbhai Bridge Northbound entry onto Sabarmati riverfront corridor",
    },
    {
        "id": "cam02",
        "camera_code": "CAM-002",
        "name": "02 Janpath",
        "latitude": 23.0612,
        "longitude": 72.5801,
        "district": "Ahmedabad",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "police_station": "Sabarmati Police Station",
        "road_name": "Janpath Road Junction",
        "direction": "East",
        "heading": 90.0,
        "field_of_view": 85.0,
        "coverage_distance": 175.0,
        "camera_type": "ANPR",
        "has_valid_location": True,
        "location_description": "Janpath Road 4-way arterial intersection towards Sabarmati D-Cabin",
    },
    {
        "id": "cam03",
        "camera_code": "CAM-003",
        "name": "03 O.N.G.C. Office",
        "latitude": 23.1028,
        "longitude": 72.5856,
        "district": "Ahmedabad",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "police_station": "Chandkheda Police Station",
        "road_name": "ONGC Office Marg",
        "direction": "North",
        "heading": 0.0,
        "field_of_view": 90.0,
        "coverage_distance": 190.0,
        "camera_type": "ANPR / HIGH_SECURITY",
        "has_valid_location": True,
        "location_description": "ONGC Western Regional Headquarters Main Perimeter Gate & Transit Highway",
    },
    {
        "id": "cam04",
        "camera_code": "CAM-004",
        "name": "04 Paldi Circle",
        "latitude": 23.0135,
        "longitude": 72.5624,
        "district": "Ahmedabad",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "police_station": "Paldi Police Station",
        "road_name": "Paldi Crossroad",
        "direction": "South",
        "heading": 180.0,
        "field_of_view": 80.0,
        "coverage_distance": 160.0,
        "camera_type": "ANPR / PTZ",
        "has_valid_location": True,
        "location_description": "Paldi Circle Southward transit towards Ellisbridge and Ashram Road",
    },
    {
        "id": "cam05",
        "camera_code": "CAM-005",
        "name": "05 Visat teen Rasta",
        "latitude": 23.0945,
        "longitude": 72.5882,
        "district": "Ahmedabad",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "police_station": "Sabarmati Police Station",
        "road_name": "Visat Teen Rasta Circle",
        "direction": "West",
        "heading": 270.0,
        "field_of_view": 85.0,
        "coverage_distance": 180.0,
        "camera_type": "ANPR",
        "has_valid_location": True,
        "location_description": "Visat 3-Way Junction connecting Sabarmati to Gandhinagar Highway",
    },
    {
        "id": "cam06",
        "camera_code": "CAM-006",
        "name": "06 Timbavadi gate-Junagadh",
        "latitude": 21.5167,
        "longitude": 70.4500,
        "district": "Junagadh",
        "city": "Junagadh",
        "state": "Gujarat",
        "police_station": "Junagadh 'A' Division Police Station",
        "road_name": "Timbavadi Gate Chowk",
        "direction": "South",
        "heading": 180.0,
        "field_of_view": 85.0,
        "coverage_distance": 180.0,
        "camera_type": "ANPR / TOLL",
        "has_valid_location": True,
        "location_description": "Timbavadi Gate Western Checkpost entry into Junagadh Urban limits",
    },
    {
        "id": "cam07",
        "camera_code": "CAM-007",
        "name": "07 hero-showroom-gir-somnath",
        "latitude": 20.9000,
        "longitude": 70.3667,
        "district": "Gir Somnath",
        "city": "Veraval",
        "state": "Gujarat",
        "police_station": "Veraval Police Station",
        "road_name": "National Highway 51 Veraval",
        "direction": "East",
        "heading": 90.0,
        "field_of_view": 90.0,
        "coverage_distance": 200.0,
        "camera_type": "ANPR / HIGHWAY",
        "has_valid_location": True,
        "location_description": "NH-51 Veraval Somnath Highway arterial commercial corridor",
    },
    {
        "id": "cam08",
        "camera_code": "CAM-008",
        "name": "08 majewadi-gate-junagadh",
        "latitude": 21.5280,
        "longitude": 70.4630,
        "district": "Junagadh",
        "city": "Junagadh",
        "state": "Gujarat",
        "police_station": "Junagadh 'B' Division Police Station",
        "road_name": "Majewadi Gate Entry",
        "direction": "North",
        "heading": 0.0,
        "field_of_view": 85.0,
        "coverage_distance": 170.0,
        "camera_type": "ANPR",
        "has_valid_location": True,
        "location_description": "Historic Majewadi Gate Northbound arterial checkpoint",
    },
    {
        "id": "cam09",
        "camera_code": "CAM-009",
        "name": "09 new-bypass-near-by-circle-junagadh-2",
        "latitude": 21.5050,
        "longitude": 70.4780,
        "district": "Junagadh",
        "city": "Junagadh",
        "state": "Gujarat",
        "police_station": "Junagadh Rural Police Station",
        "road_name": "Junagadh Bypass Ring Road",
        "direction": "East",
        "heading": 90.0,
        "field_of_view": 90.0,
        "coverage_distance": 210.0,
        "camera_type": "ANPR / SPEED_MONITOR",
        "has_valid_location": True,
        "location_description": "New Bypass Ring Road Circle connecting Rajkot-Junagadh-Somnath artery",
    },
    {
        "id": "cam10",
        "camera_code": "CAM-010",
        "name": "10 char-chowk-road-2-junagadh",
        "latitude": 21.5210,
        "longitude": 70.4590,
        "district": "Junagadh",
        "city": "Junagadh",
        "state": "Gujarat",
        "police_station": "Junagadh 'A' Division Police Station",
        "road_name": "Char Chowk Road Axis",
        "direction": "West",
        "heading": 270.0,
        "field_of_view": 85.0,
        "coverage_distance": 165.0,
        "camera_type": "ANPR / CROWD",
        "has_valid_location": True,
        "location_description": "Char Chowk high-density commercial crossroads in central Junagadh",
    },
    {
        "id": "cam11",
        "camera_code": "CAM-011",
        "name": "11 dolatpara-junagadh",
        "latitude": 21.5420,
        "longitude": 70.4710,
        "district": "Junagadh",
        "city": "Junagadh",
        "state": "Gujarat",
        "police_station": "Junagadh 'C' Division Police Station",
        "road_name": "Dolatpara Industrial Corridor",
        "direction": "North",
        "heading": 0.0,
        "field_of_view": 80.0,
        "coverage_distance": 180.0,
        "camera_type": "ANPR / INDUSTRIAL",
        "has_valid_location": True,
        "location_description": "Dolatpara GIDC Industrial logistics entry point",
    },
    {
        "id": "cam12",
        "camera_code": "CAM-012",
        "name": "12 Tri Mandir Adalaj Tollnaka",
        "latitude": 23.1667,
        "longitude": 72.5833,
        "district": "Gandhinagar",
        "city": "Adalaj",
        "state": "Gujarat",
        "police_station": "Adalaj Police Station",
        "road_name": "Adalaj Tollnaka Expressway",
        "direction": "North",
        "heading": 0.0,
        "field_of_view": 90.0,
        "coverage_distance": 220.0,
        "camera_type": "ANPR / TOLL",
        "has_valid_location": True,
        "location_description": "Ahmedabad-Gandhinagar Tri Mandir Adalaj toll plaza corridor",
    },
    {
        "id": "cam13",
        "camera_code": "CAM-013",
        "name": "13 CN Vidhyalaya",
        "latitude": 23.0210,
        "longitude": 72.5480,
        "district": "Ahmedabad",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "police_station": "Ellisbridge Police Station",
        "road_name": "Ambawadi Main Road",
        "direction": "East",
        "heading": 90.0,
        "field_of_view": 85.0,
        "coverage_distance": 150.0,
        "camera_type": "ANPR / SCHOOL_ZONE",
        "has_valid_location": True,
        "location_description": "CN Vidhyalaya Ambawadi education and pedestrian transit corridor",
    },
    {
        "id": "cam14",
        "camera_code": "CAM-014",
        "name": "14 Delight RLVD",
        "latitude": 23.0350,
        "longitude": 72.5600,
        "district": "Ahmedabad",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "police_station": "Navrangpura Police Station",
        "road_name": "University Road Junction",
        "direction": "South",
        "heading": 180.0,
        "field_of_view": 85.0,
        "coverage_distance": 160.0,
        "camera_type": "RLVD / ANPR",
        "has_valid_location": True,
        "location_description": "Gujarat University Road Red Light Violation Detection node",
    },
    {
        "id": "cam15",
        "camera_code": "CAM-015",
        "name": "15 Suvidha park",
        "latitude": 23.0180,
        "longitude": 72.5350,
        "district": "Ahmedabad",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "police_station": "Satellite Police Station",
        "road_name": "Suvidha Park Crossroad",
        "direction": "West",
        "heading": 270.0,
        "field_of_view": 85.0,
        "coverage_distance": 160.0,
        "camera_type": "ANPR",
        "has_valid_location": True,
        "location_description": "Satellite area Suvidha Park residential-commercial junction",
    },
    {
        "id": "cam16",
        "camera_code": "CAM-016",
        "name": "16 Visat P2",
        "latitude": 23.0970,
        "longitude": 72.5890,
        "district": "Ahmedabad",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "police_station": "Sabarmati Police Station",
        "road_name": "Visat Perimeter Sector 2",
        "direction": "North",
        "heading": 0.0,
        "field_of_view": 85.0,
        "coverage_distance": 185.0,
        "camera_type": "ANPR / PTZ",
        "has_valid_location": True,
        "location_description": "Visat Circle Northward Perimeter secondary tracking node",
    },
    {
        "id": "cam17",
        "camera_code": "CAM-017",
        "name": "17 Rajkot Bus Port CCTV",
        "latitude": 22.3039,
        "longitude": 70.8022,
        "district": "Rajkot",
        "city": "Rajkot",
        "state": "Gujarat",
        "police_station": "Rajkot 'A' Division Police Station",
        "road_name": "Central Bus Port Terminal",
        "direction": "East",
        "heading": 90.0,
        "field_of_view": 90.0,
        "coverage_distance": 190.0,
        "camera_type": "ANPR / TRANSIT_HUB",
        "has_valid_location": True,
        "location_description": "Rajkot Central GSRTC Bus Terminal passenger & vehicle concourse",
    },
    {
        "id": "cam18",
        "camera_code": "CAM-018",
        "name": "18 Rajkot CCTV",
        "latitude": 22.2980,
        "longitude": 70.7950,
        "district": "Rajkot",
        "city": "Rajkot",
        "state": "Gujarat",
        "police_station": "Pradhyuman Nagar Police Station",
        "road_name": "Trikon Baug Junction",
        "direction": "South",
        "heading": 180.0,
        "field_of_view": 85.0,
        "coverage_distance": 170.0,
        "camera_type": "ANPR / CROWD",
        "has_valid_location": True,
        "location_description": "Trikon Baug city hub and commercial pedestrian crossing",
    },
    {
        "id": "cam19",
        "camera_code": "CAM-019",
        "name": "19 KHAPARIA GRAM PANCHAYAT , TALUKA GANDEVI, DISTRICT NAVSARI",
        "latitude": 20.8167,
        "longitude": 72.9833,
        "district": "Navsari",
        "city": "Gandevi",
        "state": "Gujarat",
        "police_station": "Gandevi Police Station",
        "road_name": "Khaparia Panchayat Marg",
        "direction": "North",
        "heading": 0.0,
        "field_of_view": 85.0,
        "coverage_distance": 175.0,
        "camera_type": "ANPR / RURAL",
        "has_valid_location": True,
        "location_description": "Khaparia Gram Panchayat rural arterial node in Gandevi Taluka",
    },
    {
        "id": "cam20",
        "camera_code": "CAM-020",
        "name": "20 Mohanpura",
        "latitude": 23.0310,
        "longitude": 72.5920,
        "district": "Ahmedabad",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "police_station": "Kalupur Police Station",
        "road_name": "Mohanpura Relief Road",
        "direction": "West",
        "heading": 270.0,
        "field_of_view": 80.0,
        "coverage_distance": 150.0,
        "camera_type": "ANPR / OLD_CITY",
        "has_valid_location": True,
        "location_description": "Kalupur Relief Road Mohanpura gate entry into old city market",
    },
    {
        "id": "cam21",
        "camera_code": "CAM-021",
        "name": "23 Patan Dethali Char Rasta",
        "latitude": 23.8500,
        "longitude": 72.1200,
        "district": "Patan",
        "city": "Patan",
        "state": "Gujarat",
        "police_station": "Patan City Police Station",
        "road_name": "Dethali Char Rasta",
        "direction": "North",
        "heading": 0.0,
        "field_of_view": 85.0,
        "coverage_distance": 190.0,
        "camera_type": "ANPR / HIGHWAY",
        "has_valid_location": True,
        "location_description": "Dethali 4-way crossroads on SH-7 Patan-Mehsana corridor",
    },
    {
        "id": "cam22",
        "camera_code": "CAM-022",
        "name": "28 BK Mervada tran Rasta",
        "latitude": 24.1700,
        "longitude": 72.4300,
        "district": "Banaskantha",
        "city": "Palanpur",
        "state": "Gujarat",
        "police_station": "Palanpur City Police Station",
        "road_name": "Mervada Tran Rasta NH-27",
        "direction": "East",
        "heading": 90.0,
        "field_of_view": 90.0,
        "coverage_distance": 220.0,
        "camera_type": "ANPR / BORDER_HIGHWAY",
        "has_valid_location": True,
        "location_description": "National Highway 27 Palanpur Mervada 3-Way strategic border artery",
    },
    {
        "id": "cam23",
        "camera_code": "CAM-023",
        "name": "30 kheram",
        "latitude": 22.7500,
        "longitude": 72.6800,
        "district": "Kheda",
        "city": "Kheda",
        "state": "Gujarat",
        "police_station": "Kheda Town Police Station",
        "road_name": "Kheram Circle NH-48",
        "direction": "South",
        "heading": 180.0,
        "field_of_view": 90.0,
        "coverage_distance": 200.0,
        "camera_type": "ANPR / EXPRESSWAY",
        "has_valid_location": True,
        "location_description": "NH-48 Golden Quadrilateral Kheram flyover transit node",
    },
    {
        "id": "cam24",
        "camera_code": "CAM-024",
        "name": "33 dehgam",
        "latitude": 23.1670,
        "longitude": 72.8170,
        "district": "Gandhinagar",
        "city": "Dehgam",
        "state": "Gujarat",
        "police_station": "Dehgam Police Station",
        "road_name": "Dehgam Central Crossroad",
        "direction": "East",
        "heading": 90.0,
        "field_of_view": 85.0,
        "coverage_distance": 180.0,
        "camera_type": "ANPR",
        "has_valid_location": True,
        "location_description": "Dehgam-Gandhinagar SH-68 central municipal junction",
    },
    {
        "id": "cam25",
        "camera_code": "CAM-025",
        "name": "34 dhanori",
        "latitude": 20.8500,
        "longitude": 73.0100,
        "district": "Navsari",
        "city": "Gandevi",
        "state": "Gujarat",
        "police_station": "Gandevi Police Station",
        "road_name": "Dhanori State Highway",
        "direction": "West",
        "heading": 270.0,
        "field_of_view": 85.0,
        "coverage_distance": 175.0,
        "camera_type": "ANPR",
        "has_valid_location": True,
        "location_description": "Dhanori-Gandevi connector highway surveillance node",
    },
    {
        "id": "cam26",
        "camera_code": "CAM-026",
        "name": "35 TANKAL",
        "latitude": 20.7800,
        "longitude": 73.0500,
        "district": "Navsari",
        "city": "Chikhli",
        "state": "Gujarat",
        "police_station": "Chikhli Police Station",
        "road_name": "Tankal Chikhli Road",
        "direction": "North",
        "heading": 0.0,
        "field_of_view": 85.0,
        "coverage_distance": 175.0,
        "camera_type": "ANPR",
        "has_valid_location": True,
        "location_description": "Tankal-Chikhli rural commerce corridor and bus route",
    },
    {
        "id": "cam27",
        "camera_code": "CAM-027",
        "name": "36 bilimora",
        "latitude": 20.7600,
        "longitude": 72.9600,
        "district": "Navsari",
        "city": "Bilimora",
        "state": "Gujarat",
        "police_station": "Bilimora Police Station",
        "road_name": "Bilimora Railway Station Road",
        "direction": "South",
        "heading": 180.0,
        "field_of_view": 85.0,
        "coverage_distance": 160.0,
        "camera_type": "ANPR / TRANSIT",
        "has_valid_location": True,
        "location_description": "Bilimora Western Railway Station main approach concourse",
    },
    {
        "id": "cam28",
        "camera_code": "CAM-028",
        "name": "37 bilimora",
        "latitude": 20.7650,
        "longitude": 72.9680,
        "district": "Navsari",
        "city": "Bilimora",
        "state": "Gujarat",
        "police_station": "Bilimora Police Station",
        "road_name": "Bilimora Town Market Circle",
        "direction": "East",
        "heading": 90.0,
        "field_of_view": 85.0,
        "coverage_distance": 165.0,
        "camera_type": "ANPR / CROWD",
        "has_valid_location": True,
        "location_description": "Bilimora town market circle high-density commercial zone",
    },
    {
        "id": "cam29",
        "camera_code": "CAM-029",
        "name": "38 bilimora",
        "latitude": 20.7700,
        "longitude": 72.9750,
        "district": "Navsari",
        "city": "Bilimora",
        "state": "Gujarat",
        "police_station": "Bilimora Police Station",
        "road_name": "Bilimora Coastal Highway",
        "direction": "North",
        "heading": 0.0,
        "field_of_view": 90.0,
        "coverage_distance": 190.0,
        "camera_type": "ANPR / COASTAL",
        "has_valid_location": True,
        "location_description": "Bilimora coastal road surveillance and port transit artery",
    },
    {
        "id": "cam30",
        "camera_code": "CAM-030",
        "name": "Gandhidham Rambaugh p2",
        "latitude": 23.0753,
        "longitude": 70.1337,
        "district": "Kutch",
        "city": "Gandhidham",
        "state": "Gujarat",
        "police_station": "Gandhidham 'A' Division Police Station",
        "road_name": "Rambaugh Road Sector 2",
        "direction": "West",
        "heading": 270.0,
        "field_of_view": 90.0,
        "coverage_distance": 200.0,
        "camera_type": "ANPR / PORT_CORRIDOR",
        "has_valid_location": True,
        "location_description": "Gandhidham Kandla Port feeder corridor Rambaugh Sector 2",
    },
]


def calculate_coverage_wedge_points(
    lat: float, lon: float, heading_deg: float, fov_deg: float, distance_meters: float, num_points: int = 12
) -> List[List[float]]:
    """
    Computes a true geodesic sector/wedge polygon representing camera FOV coverage.
    Returns array of [latitude, longitude] pairs starting at camera origin,
    sweeping through arc, and returning to origin.
    """
    earth_radius = 6378137.0  # WGS84 meters
    origin = [lat, lon]
    points = [origin]

    half_fov = fov_deg / 2.0
    start_angle = heading_deg - half_fov
    end_angle = heading_deg + half_fov

    lat_rad = math.radians(lat)
    lon_rad = math.radians(lon)
    dist_ratio = distance_meters / earth_radius

    for i in range(num_points + 1):
        fraction = i / num_points
        angle_deg = start_angle + fraction * (end_angle - start_angle)
        bearing_rad = math.radians(angle_deg)

        point_lat_rad = math.asin(
            math.sin(lat_rad) * math.cos(dist_ratio)
            + math.cos(lat_rad) * math.sin(dist_ratio) * math.cos(bearing_rad)
        )
        point_lon_rad = lon_rad + math.atan2(
            math.sin(bearing_rad) * math.sin(dist_ratio) * math.cos(lat_rad),
            math.cos(dist_ratio) - math.sin(lat_rad) * math.sin(point_lat_rad),
        )

        points.append([math.degrees(point_lat_rad), math.degrees(point_lon_rad)])

    points.append(origin)  # Close the polygon
    return points


def get_cctv_gis_dict() -> Dict[str, Dict[str, Any]]:
    """Returns mapping of camera ID -> GIS Metadata."""
    return {c["id"].lower(): c for c in GUJARAT_CCTV_GIS_REGISTRY}


def get_all_cctv_gis_nodes() -> List[Dict[str, Any]]:
    """Returns all 30 GIS enriched cameras with pre-computed coverage polygon wedges."""
    nodes = []
    for c in GUJARAT_CCTV_GIS_REGISTRY:
        node = dict(c)
        node["coverage_polygon"] = calculate_coverage_wedge_points(
            lat=c["latitude"],
            lon=c["longitude"],
            heading_deg=c["heading"],
            fov_deg=c["field_of_view"],
            distance_meters=c["coverage_distance"],
        )
        nodes.append(node)
    return nodes
